import { Dimensions, StyleSheet } from 'react-native';
import type { AppTheme } from '../theme';

export const screenWidth = Dimensions.get('window').width;
export const screenHeight = Dimensions.get('window').height;
export const isSmallScreen = screenWidth < 380;
export const isMediumScreen = screenWidth >= 380 && screenWidth < 480;
export const collapsedPlayerTop = screenHeight - (isSmallScreen ? 138 : 146);
export const detailBackgroundFadeHeight = isSmallScreen ? 132 : 160;

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    accessContent: {
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 16,
    },
    playerScreen: {
      flex: 1,
    },
    playerContent: {
      paddingHorizontal: isSmallScreen ? 12 : 16,
      paddingTop: isSmallScreen ? 8 : 12,
      paddingBottom: isSmallScreen ? 265 : 280,
      gap: isSmallScreen ? 12 : 16,
    },
    appHeader: {
      alignItems: 'center',
      backgroundColor: theme.background,
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
      paddingHorizontal: isSmallScreen ? 12 : 16,
      paddingTop: isSmallScreen ? 8 : 12,
      paddingBottom: 10,
    },
    brandRow: {
      alignItems: 'center',
      flexDirection: 'row',
      flexShrink: 1,
      gap: 10,
    },
    headerActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    brandMark: {
      alignItems: 'center',
      borderRadius: 999,
      height: 40,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 40,
    },
    brandMarkText: {
      color: theme.accentText,
      fontSize: 18,
      fontWeight: '900',
    },
    brandName: {
      color: theme.text,
      flexShrink: 1,
      fontSize: isSmallScreen ? 15 : isMediumScreen ? 16 : 17,
      fontWeight: '800',
    },
    headerPill: {
      borderColor: theme.borderStrong,
      borderRadius: 999,
      borderWidth: 1,
      color: theme.mutedStrong,
      fontSize: 12,
      fontWeight: '800',
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    themeButton: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 7,
      minHeight: 42,
      paddingHorizontal: 12,
    },
    themeButtonLabel: {
      color: theme.text,
      fontSize: 12,
      fontWeight: '900',
    },
    logoutButton: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },
    searchPill: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 48,
      paddingHorizontal: 16,
    },
    searchInput: {
      color: theme.text,
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      minHeight: 48,
      paddingVertical: 0,
    },
    searchPanelHeader: {
      gap: 4,
      paddingTop: 4,
    },
    tabContentAnimator: {
      gap: isSmallScreen ? 12 : 16,
    },
    panelTabs: {
      backgroundColor: theme.surfaceSoft,
      borderRadius: 999,
      flexDirection: 'row',
      gap: 4,
      padding: 4,
    },
    panelTab: {
      alignItems: 'center',
      borderRadius: 999,
      flex: 1,
      justifyContent: 'center',
      minHeight: 42,
    },
    panelTabActive: {
      backgroundColor: theme.secondary,
    },
    panelTabLabel: {
      color: theme.muted,
      fontSize: 13,
      fontWeight: '900',
    },
    panelTabLabelActive: {
      color: theme.accentText,
    },
    sourceScroller: {
      gap: 8,
      paddingRight: 16,
    },
    sourceChip: {
      alignItems: 'center',
      borderColor: theme.borderStrong,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      minHeight: 38,
      paddingHorizontal: 13,
    },
    sourceChipActive: {
      backgroundColor: theme.text,
      borderColor: theme.text,
    },
    sourceChipLabel: {
      color: theme.mutedStrong,
      fontSize: 13,
      fontWeight: '900',
    },
    sourceChipLabelActive: {
      color: theme.background,
    },
    sourceChipCount: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: '900',
    },
    sourceChipCountActive: {
      color: '#4b3f36',
    },
    previewDeck: {
      alignItems: 'flex-start',
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 14,
      padding: 18,
    },
    previewTitle: {
      color: theme.text,
      fontSize: 35,
      fontWeight: '900',
      lineHeight: 38,
    },
    previewCopy: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 22,
    },
    authCard: {
      backgroundColor: theme.surfaceStrong,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 12,
      padding: 16,
    },
    tabRow: {
      backgroundColor: theme.surfaceSoft,
      borderRadius: 999,
      flexDirection: 'row',
      gap: 4,
      padding: 4,
    },
    tabButton: {
      alignItems: 'center',
      borderRadius: 999,
      flex: 1,
      justifyContent: 'center',
      minHeight: isSmallScreen ? 38 : 42,
    },
    tabButtonActive: {
      backgroundColor: theme.text,
    },
    tabLabel: {
      color: theme.muted,
      fontSize: isSmallScreen ? 11 : 13,
      fontWeight: '900',
    },
    tabLabelActive: {
      color: theme.background,
    },
    eyebrow: {
      color: theme.secondary,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    cardTitle: {
      color: theme.text,
      fontSize: 25,
      fontWeight: '900',
    },
    caption: {
      color: theme.muted,
      fontSize: 14,
      lineHeight: 20,
    },
    input: {
      backgroundColor: theme.field,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      color: theme.text,
      minHeight: 52,
      paddingHorizontal: 15,
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: theme.accent,
      borderRadius: 999,
      justifyContent: 'center',
      minHeight: 52,
    },
    disabledButton: {
      opacity: 0.5,
    },
    primaryButtonLabel: {
      color: theme.accentText,
      fontSize: 15,
      fontWeight: '900',
    },
    googleButton: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.borderStrong,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      minHeight: 52,
    },
    googleButtonLabel: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '800',
    },
    textButton: {
      alignSelf: 'flex-start',
      paddingVertical: 4,
    },
    textButtonLabel: {
      color: theme.mutedStrong,
      fontSize: 14,
      fontWeight: '800',
      textDecorationLine: 'underline',
    },
    feedback: {
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    feedbackError: {
      backgroundColor: 'rgba(255,111,125,0.12)',
      borderColor: 'rgba(255,111,125,0.24)',
    },
    feedbackNotice: {
      backgroundColor: 'rgba(85,214,194,0.1)',
      borderColor: 'rgba(85,214,194,0.24)',
    },
    feedbackText: {
      color: theme.text,
      fontSize: 14,
      lineHeight: 20,
    },
    signalDeck: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 12,
      padding: isSmallScreen ? 12 : 16,
      alignItems: 'center',
    },
    deckCopy: {
      gap: 8,
      width: '100%',
      alignItems: 'center',
    },
    trackTitle: {
      color: theme.text,
      fontSize: isSmallScreen ? 26 : isMediumScreen ? 30 : 34,
      fontWeight: '900',
      lineHeight: isSmallScreen ? 30 : isMediumScreen ? 34 : 38,
      textAlign: 'center',
    },
    trackArtist: {
      color: theme.muted,
      fontSize: isSmallScreen ? 13 : 15,
      lineHeight: isSmallScreen ? 18 : 22,
      textAlign: 'center',
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 4,
    },
    chip: {
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      color: theme.mutedStrong,
      fontSize: 12,
      fontWeight: '800',
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    heroActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'center',
      marginTop: 6,
    },
    heroPlayButton: {
      alignItems: 'center',
      borderRadius: 999,
      flexDirection: 'row',
      gap: 8,
      minHeight: 42,
      overflow: 'hidden',
      paddingHorizontal: 17,
    },
    heroPlayLabel: {
      color: theme.accentText,
      fontSize: 13,
      fontWeight: '900',
    },
    heroSubtleButton: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 7,
      minHeight: 42,
      paddingHorizontal: 14,
    },
    heroSubtleButtonActive: {
      backgroundColor: 'rgba(255,122,89,0.13)',
      borderColor: 'rgba(255,122,89,0.28)',
    },
    heroSubtleButtonDisabled: {
      opacity: 0.45,
    },
    heroSubtleLabel: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '900',
    },
    waveCard: {
      alignItems: 'flex-end',
      backgroundColor: 'rgba(85,214,194,0.08)',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 5,
      height: 108,
      padding: 14,
    },
    waveBar: {
      backgroundColor: theme.secondary,
      borderRadius: 999,
      flex: 1,
      minHeight: 20,
    },
    sectionHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    sectionTitle: {
      color: theme.text,
      fontSize: isSmallScreen ? 17 : isMediumScreen ? 19 : 21,
      fontWeight: '900',
    },
    sectionAction: {
      color: theme.mutedStrong,
      fontSize: isSmallScreen ? 11 : 13,
      fontWeight: '800',
    },
    trackList: {
      gap: 8,
    },
    trackRow: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.surfaceSoft,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: isSmallScreen ? 8 : 10,
      minHeight: isSmallScreen ? 56 : 64,
      paddingHorizontal: isSmallScreen ? 8 : 10,
    },
    trackRowActive: {
      backgroundColor: 'rgba(85,214,194,0.12)',
      borderColor: 'rgba(85,214,194,0.26)',
    },
    trackNumber: {
      color: theme.muted,
      fontSize: 13,
      fontWeight: '900',
      width: 24,
    },
    trackNumberActive: {
      color: theme.secondary,
    },
    trackMeta: {
      flex: 1,
      minWidth: 0,
    },
    trackName: {
      color: theme.text,
      fontSize: isSmallScreen ? 13 : 15,
      fontWeight: '900',
    },
    trackSubtext: {
      color: theme.muted,
      fontSize: isSmallScreen ? 11 : 12,
      marginTop: 2,
    },
    trackDuration: {
      color: theme.muted,
      fontSize: isSmallScreen ? 11 : 12,
      fontWeight: '800',
    },
    rowIconButton: {
      alignItems: 'center',
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    queueCard: {
      backgroundColor: 'rgba(245,193,93,0.08)',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 8,
      padding: 14,
    },
    queueItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      minHeight: 54,
    },
    emptyCard: {
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 6,
      padding: 14,
    },
    emptyTitle: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '900',
    },
    playlistGrid: {
      gap: 10,
    },
    collectionScroller: {
      gap: 10,
      paddingRight: 16,
    },
    libraryOverviewCard: {
      alignItems: 'center',
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 18,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 13,
      padding: 15,
    },
    libraryOverviewIcon: {
      alignItems: 'center',
      backgroundColor: theme.accent,
      borderRadius: 14,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    libraryOverviewCopy: {
      flex: 1,
      minWidth: 0,
    },
    libraryOverviewTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '900',
    },
    libraryOverviewMeta: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 3,
    },
    playlistCard: {
      backgroundColor: 'rgba(245,193,93,0.08)',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 4,
      padding: 14,
    },
    playlistTitle: {
      color: theme.text,
      fontSize: isSmallScreen ? 14 : isMediumScreen ? 15 : 16,
      fontWeight: '900',
    },
    profileCard: {
      alignItems: 'center',
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 12,
      padding: 16,
    },
    profileAvatar: {
      alignItems: 'center',
      backgroundColor: theme.secondary,
      borderRadius: 999,
      height: 58,
      justifyContent: 'center',
      width: 58,
    },
    profileAvatarText: {
      color: theme.accentText,
      fontSize: 24,
      fontWeight: '900',
    },
    profileCopy: {
      flex: 1,
      minWidth: 0,
    },
    profileName: {
      color: theme.text,
      fontSize: isSmallScreen ? 18 : isMediumScreen ? 20 : 22,
      fontWeight: '900',
    },
    statsRow: {
      flexDirection: 'row',
      gap: 8,
    },
    statCard: {
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      gap: 4,
      padding: 12,
    },
    statValue: {
      color: theme.text,
      fontSize: 23,
      fontWeight: '900',
    },
    statLabel: {
      color: theme.muted,
      fontSize: 11,
      fontWeight: '800',
    },
    managementCard: {
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 12,
      padding: 14,
    },
    secondaryAction: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      minHeight: 42,
      paddingHorizontal: 14,
    },
    secondaryActionLabel: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '900',
    },
    createPlaylistRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
    },
    playlistInput: {
      flex: 1,
    },
    addButton: {
      alignItems: 'center',
      borderRadius: 999,
      height: 52,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 52,
    },
    playlistScroller: {
      gap: 8,
      paddingRight: 12,
    },
    playlistChip: {
      borderColor: theme.borderStrong,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 13,
      paddingVertical: 9,
    },
    playlistChipActive: {
      backgroundColor: theme.text,
    },
    playlistChipText: {
      color: theme.mutedStrong,
      fontSize: 13,
      fontWeight: '900',
    },
    playlistChipTextActive: {
      color: theme.background,
    },
    playlistTrackRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    playlistTrackPressable: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 54,
    },
    removeButton: {
      alignItems: 'center',
      backgroundColor: 'rgba(255,111,125,0.1)',
      borderRadius: 999,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
    deletePlaylistButton: {
      alignSelf: 'flex-start',
      paddingVertical: 4,
    },
    deletePlaylistText: {
      color: theme.danger,
      fontSize: 13,
      fontWeight: '900',
      textDecorationLine: 'underline',
    },
    deleteAccountButton: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      paddingVertical: 12,
      alignSelf: 'auto',
    },
    deleteAccountText: {
      textDecorationLine: 'none',
      fontWeight: '600',
    },
    settingsContent: {
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 72,
      gap: 22,
    },
    settingsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 18,
    },
    settingsBackButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      width: 40,
      height: 40,
      justifyContent: 'center',
      marginLeft: -10,
    },
    settingsBackText: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '700',
    },
    settingsTitle: {
      color: theme.text,
      fontSize: 17,
      fontWeight: '900',
    },
    settingsCard: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderWidth: 1,
      borderRadius: 12,
      padding: 16,
      gap: 14,
    },
    settingsCardTitle: {
      color: theme.text,
      fontSize: 17,
      fontWeight: '800',
    },
    fieldLabel: {
      color: theme.mutedStrong,
      fontSize: 13,
      fontWeight: '800',
      marginTop: 2,
      marginBottom: -6,
    },
    filePickerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderColor: theme.border,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderRadius: 12,
      backgroundColor: theme.field,
    },
    filePickerText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
      flexShrink: 1,
    },
    spotifyProfileContainer: {
      flex: 1,
    },
    spotifyHeader: {
      alignItems: 'center',
      paddingVertical: 32,
      position: 'relative',
    },
    spotifySettingsButton: {
      position: 'absolute',
      top: 16,
      right: 16,
      padding: 8,
      zIndex: 10,
    },
    spotifyAvatarContainer: {
      width: 120,
      height: 120,
      borderRadius: 60,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
    },
    spotifyAvatarLarge: {
      width: 120,
      height: 120,
      borderRadius: 60,
    },
    spotifyAvatarPlaceholder: {
      backgroundColor: theme.secondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    spotifyAvatarInitial: {
      color: theme.accentText,
      fontSize: 48,
      fontWeight: '900',
    },
    spotifyName: {
      color: theme.text,
      fontSize: 28,
      fontWeight: '900',
      marginBottom: 6,
      letterSpacing: -0.5,
    },
    spotifyStatsInline: {
      color: theme.muted,
      fontSize: 14,
      fontWeight: '600',
    },
    spotifyPlaylistsSection: {
      paddingHorizontal: 16,
      paddingBottom: 40,
    },
    spotifySectionTitle: {
      color: theme.text,
      fontSize: 20,
      fontWeight: '800',
      marginBottom: 16,
      marginTop: 8,
    },
    spotifyCreatePlaylistRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      gap: 16,
    },
    spotifyCreateIconContainer: {
      width: 48,
      height: 48,
      backgroundColor: theme.accent,
      borderRadius: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    spotifyCreateInput: {
      flex: 1,
      color: theme.text,
      fontSize: 16,
      fontWeight: '600',
      height: 48,
    },
    spotifyCreateButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: theme.surfaceSoft,
      borderRadius: 999,
    },
    spotifyCreateButtonText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '700',
    },
    spotifyPlaylistsList: {
      gap: 16,
    },
    spotifyPlaylistRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    },
    spotifyPlaylistRowActive: {
      backgroundColor: theme.surfaceSoft,
      borderRadius: 8,
    },
    spotifyPlaylistCover: {
      width: 48,
      height: 48,
      backgroundColor: theme.surface,
      borderRadius: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    spotifyPlaylistMeta: {
      flex: 1,
      justifyContent: 'center',
    },
    spotifyPlaylistName: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 2,
    },
    spotifyPlaylistNameInput: {
      borderBottomWidth: 1,
      borderBottomColor: theme.accent,
      paddingVertical: 0,
      minWidth: 120,
    },
    spotifyPlaylistSubtext: {
      color: theme.muted,
      fontSize: 13,
    },
    spotifyPlaylistDelete: {
      padding: 8,
    },
    spotifyEmptyState: {
      alignItems: 'center',
      paddingVertical: 32,
    },
    spotifyEmptyStateText: {
      color: theme.muted,
      fontSize: 15,
    },
    spotifySelectedPlaylistContainer: {
      marginTop: 32,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      paddingTop: 16,
    },
    spotifySettingsSection: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 18,
      borderWidth: 1,
      gap: 14,
      padding: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: theme.mode === 'dark' ? 0.18 : 0.08,
      shadowRadius: 18,
    },
    spotifySettingsSectionTitle: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 2,
    },
    spotifyInput: {
      backgroundColor: theme.field,
      borderColor: theme.border,
      borderRadius: 12,
      borderWidth: 1,
      color: theme.text,
      fontSize: 15,
      fontWeight: '700',
      paddingHorizontal: 16,
      paddingVertical: 14,
      minHeight: 52,
    },
    modernSettingsProfileCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 20,
      borderWidth: 1,
      padding: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: theme.mode === 'dark' ? 0.2 : 0.08,
      shadowRadius: 20,
    },
    modernAvatarContainer: {
      position: 'relative',
      marginRight: 16,
    },
    modernAvatar: {
      width: 64,
      height: 64,
      borderRadius: 32,
    },
    modernAvatarInitial: {
      color: theme.accentText,
      fontSize: 28,
      fontWeight: '900',
    },
    cameraBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: '#1db954',
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: theme.background,
    },
    profileCameraBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: '#1db954',
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: theme.background,
    },
    modernProfileMeta: {
      flex: 1,
      justifyContent: 'center',
      paddingRight: 16,
    },
    modernProfileName: {
      color: theme.text,
      fontSize: 19,
      fontWeight: '800',
      marginBottom: 3,
      letterSpacing: -0.5,
    },
    modernProfileSubtitle: {
      color: theme.muted,
      fontSize: 13,
      fontWeight: '500',
    },
    languageScroller: {
      flexDirection: 'row',
      gap: 8,
      paddingTop: 2,
      paddingBottom: 2,
    },
    languageChip: {
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    languageChipActive: {
      backgroundColor: theme.accent,
      borderColor: theme.accent,
    },
    languageChipText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '800',
    },
    languageChipTextActive: {
      color: theme.accentText,
    },
    settingsPrimaryAction: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: theme.accent,
      borderRadius: 999,
      justifyContent: 'center',
      marginTop: 2,
      minHeight: 44,
      paddingHorizontal: 18,
    },
    settingsPrimaryActionText: {
      color: theme.accentText,
      fontSize: 14,
      fontWeight: '900',
    },
    settingsSecondaryAction: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      justifyContent: 'center',
      marginTop: 2,
      minHeight: 44,
      paddingHorizontal: 18,
    },
    settingsSecondaryActionText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '900',
    },
    accountRemovalSection: {
      alignItems: 'center',
      backgroundColor: theme.dangerSoft,
      borderColor:
        theme.mode === 'dark'
          ? 'rgba(255,154,165,0.28)'
          : 'rgba(201,63,77,0.2)',
      borderRadius: 18,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 14,
      padding: 16,
    },
    accountRemovalCopy: {
      flex: 1,
      gap: 3,
    },
    accountRemovalTitle: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '900',
    },
    accountRemovalDescription: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 17,
    },
    deleteAccountAction: {
      alignItems: 'center',
      backgroundColor: theme.danger,
      borderRadius: 999,
      justifyContent: 'center',
      minHeight: 42,
      paddingHorizontal: 16,
    },
    deleteAccountActionText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '900',
    },
    otpTitle: {
      color: theme.text,
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 12,
      textAlign: 'center',
    },
    otpSubtitle: {
      color: theme.muted,
      fontSize: 14,
      marginBottom: 16,
      textAlign: 'center',
    },
    otpInput: {
      fontSize: 24,
      letterSpacing: 8,
      fontWeight: 'bold',
    },
    confirmationBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.72)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    confirmationDialog: {
      width: '100%',
      maxWidth: 340,
      backgroundColor: theme.surfaceStrong,
      borderColor: theme.borderStrong,
      borderWidth: 1,
      borderRadius: 18,
      paddingHorizontal: 22,
      paddingTop: 22,
      paddingBottom: 18,
      gap: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.4,
      shadowRadius: 24,
      elevation: 12,
    },
    confirmationHeader: {
      alignItems: 'center',
      gap: 12,
      marginBottom: 20,
    },
    confirmationTitle: {
      color: theme.danger,
      fontSize: 18,
      fontWeight: '700',
    },
    confirmationMessage: {
      color: theme.muted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 24,
      textAlign: 'center',
    },
    confirmationActions: {
      flexDirection: 'row',
      gap: 12,
    },
    confirmationButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmationCancelButton: {
      backgroundColor: theme.surfaceSoft,
    },
    confirmationCancelText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
    },
    confirmationDeleteButton: {
      backgroundColor: theme.dangerSoft,
    },
    confirmationDeleteText: {
      color: theme.danger,
      fontSize: 14,
      fontWeight: '700',
    },
    sheetBackdrop: {
      backgroundColor: 'rgba(0,0,0,0.6)',
      flex: 1,
      justifyContent: 'flex-end',
    },
    actionSheet: {
      backgroundColor: theme.surfaceStrong,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      maxHeight: '82%',
      paddingHorizontal: 4,
      paddingTop: 8,
      paddingBottom: 18,
    },
    sheetDragHandle: {
      alignSelf: 'center',
      backgroundColor: theme.borderStrong,
      borderRadius: 999,
      height: 4,
      marginBottom: 12,
      width: 36,
    },
    actionSheetHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 4,
    },
    sheetDivider: {
      backgroundColor: theme.border,
      height: 1,
      marginHorizontal: 16,
      marginVertical: 8,
    },
    actionSheetList: {
      gap: 0,
    },
    actionSheetOption: {
      alignItems: 'center',
      backgroundColor: 'transparent',
      flexDirection: 'row',
      gap: 18,
      minHeight: 52,
      paddingHorizontal: 20,
    },
    actionSheetOptionDisabled: {
      opacity: 0.4,
    },
    actionSheetOptionText: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '600',
    },
    sheetCreatePlaylistRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 20,
      paddingTop: 10,
    },
    sheetCreatePlaylistInput: {
      backgroundColor: theme.field,
      borderColor: theme.border,
      borderRadius: 10,
      borderWidth: 1,
      color: theme.text,
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      minHeight: 46,
      paddingHorizontal: 12,
    },
    sheetCreatePlaylistButton: {
      alignItems: 'center',
      backgroundColor: theme.accent,
      borderRadius: 999,
      height: 46,
      justifyContent: 'center',
      width: 46,
    },
    detailScreen: {
      flex: 1,
      paddingHorizontal: isSmallScreen ? 18 : 24,
      paddingVertical: 16,
    },
    detailBackgroundFade: {
      height: detailBackgroundFadeHeight,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    detailBackgroundSolid: {
      backgroundColor: theme.background,
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: detailBackgroundFadeHeight,
    },
    detailBackgroundTopSolid: {
      backgroundColor: theme.background,
      height: detailBackgroundFadeHeight,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    detailHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 52,
      position: 'relative',
    },
    detailHeaderActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      zIndex: 2,
    },
    detailHeaderButton: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      height: 44,
      justifyContent: 'center',
      width: 44,
      zIndex: 2,
    },
    detailHeaderCopy: {
      alignItems: 'center',
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      paddingHorizontal: isSmallScreen ? 92 : 108,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 1,
    },
    detailEyebrow: {
      color: theme.secondary,
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    detailSource: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '900',
      marginTop: 2,
    },
    detailBody: {
      alignItems: 'center',
      flex: 1,
      gap: 16,
      justifyContent: 'center',
    },
    detailTrackCopy: {
      alignItems: 'center',
      gap: 8,
      width: '100%',
    },
    detailTitle: {
      color: theme.text,
      fontSize: isSmallScreen ? 27 : 32,
      fontWeight: '900',
      lineHeight: isSmallScreen ? 32 : 37,
      textAlign: 'center',
    },
    detailArtist: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 22,
      textAlign: 'center',
    },
    detailFooter: {
      gap: 14,
      paddingBottom: 12,
    },
    detailTransportRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: isSmallScreen ? 13 : 17,
      justifyContent: 'center',
    },
    detailPlayButton: {
      alignItems: 'center',
      borderRadius: 999,
      height: isSmallScreen ? 68 : 76,
      justifyContent: 'center',
      overflow: 'hidden',
      width: isSmallScreen ? 68 : 76,
    },
    detailSecondaryAction: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      minHeight: 44,
      paddingHorizontal: 16,
    },
    detailSecondaryActionActive: {
      backgroundColor: 'rgba(85,214,194,0.13)',
      borderColor: 'rgba(85,214,194,0.28)',
    },
    playlistPickerPanel: {
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 12,
      padding: 14,
    },
    detailPlaylistList: {
      gap: 8,
      maxHeight: 180,
    },
    detailPlaylistItem: {
      alignItems: 'center',
      backgroundColor: theme.field,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 56,
      paddingHorizontal: 10,
    },
    detailPlaylistItemActive: {
      borderColor: 'rgba(85,214,194,0.34)',
    },
    playlistItemIcon: {
      alignItems: 'center',
      backgroundColor: theme.accent,
      borderRadius: 8,
      height: 38,
      justifyContent: 'center',
      width: 38,
    },
    playerModalRoot: {
      flex: 1,
      overflow: 'hidden',
    },
    nowBar: {
      backgroundColor: theme.surfaceStrong,
      borderColor: theme.border,
      borderTopWidth: 1,
      bottom: 54,
      left: 0,
      position: 'absolute',
      right: 0,
      paddingTop: 6,
      paddingBottom: 6,
      paddingHorizontal: 12,
    },
    bottomTabBar: {
      alignItems: 'center',
      backgroundColor: theme.surfaceStrong,
      borderColor: theme.border,
      borderTopWidth: 1,
      bottom: 0,
      flexDirection: 'row',
      gap: 0,
      left: 0,
      paddingHorizontal: 8,
      paddingVertical: 0,
      position: 'absolute',
      right: 0,
    },
    bottomTab: {
      alignItems: 'center',
      flex: 1,
      gap: 3,
      justifyContent: 'center',
      minHeight: 54,
    },
    bottomTabLabel: {
      color: theme.muted,
      fontSize: 11,
      fontWeight: '900',
    },
    bottomTabLabelActive: {
      color: theme.accent,
    },
    miniPlayerPressable: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
    },
    miniTrackMeta: {
      flex: 1,
      justifyContent: 'center',
    },
    nowTitle: {
      color: theme.text,
      fontSize: isSmallScreen ? 13 : 15,
      fontWeight: '900',
    },
    miniTransportRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 16,
    },
    miniButton: {
      padding: 4,
    },
    miniProgressTrack: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 2,
      backgroundColor: theme.surfaceSoft,
    },
    miniProgressFill: {
      height: '100%',
      backgroundColor: theme.secondary,
    },
    transportRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: isSmallScreen ? 14 : 18,
      justifyContent: 'center',
    },
    progressMeta: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 9,
    },
    progressText: {
      color: theme.muted,
      fontSize: 11,
      fontWeight: '800',
      width: 34,
    },
    progressTrack: {
      backgroundColor: theme.border,
      borderRadius: 999,
      flex: 1,
      height: 5,
      overflow: 'hidden',
    },
    progressFill: {
      backgroundColor: theme.secondary,
      borderRadius: 999,
      height: '100%',
    },
    bootCard: {
      alignItems: 'center',
      flex: 1,
      gap: 12,
      justifyContent: 'center',
    },
    bootText: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '800',
    },

    // ── Entity detail overlay ──────────────────────────────────────────────────
    entityDetailScreen: {
      flex: 1,
      backgroundColor: theme.background,
    },
    entityDetailScrollContent: {
      paddingBottom: 120,
    },
    entityDetailHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    entityDetailBackButton: {
      alignItems: 'center',
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    entityDetailHeaderTitle: {
      color: theme.text,
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
    },
    entityDetailHero: {
      alignItems: 'center',
      gap: 10,
      paddingBottom: 20,
      paddingHorizontal: 20,
      paddingTop: 8,
    },
    entityDetailArtworkRound: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderRadius: 64,
      height: 128,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 128,
    },
    entityDetailArtworkSquare: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderRadius: 12,
      height: 128,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 128,
    },
    entityDetailArtworkImage: {
      height: '100%',
      width: '100%',
    },
    entityDetailArtworkInitial: {
      color: theme.text,
      fontSize: 44,
      fontWeight: '800',
    },
    entityDetailName: {
      color: theme.text,
      fontSize: 22,
      fontWeight: '800',
      textAlign: 'center',
    },
    entityDetailSubtitle: {
      color: theme.muted,
      fontSize: 13,
      textAlign: 'center',
    },
    entityDetailActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
    entityDetailPlayAllButton: {
      alignItems: 'center',
      borderRadius: 24,
      flexDirection: 'row',
      gap: 7,
      overflow: 'hidden',
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    entityDetailPlayAllText: {
      color: theme.accentText,
      fontSize: 14,
      fontWeight: '700',
    },
    entityDetailShuffleButton: {
      alignItems: 'center',
      borderColor: theme.border,
      borderRadius: 24,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 7,
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    entityDetailShuffleText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
    },

    // ── Queue view in track detail ─────────────────────────────────────────────
    queueSection: {
      gap: 4,
      marginTop: 8,
    },
    queueSectionToggle: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 4,
      paddingVertical: 8,
    },
    queueSectionLabel: {
      color: theme.muted,
      flex: 1,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    queueSectionCount: {
      color: theme.muted,
      fontSize: 12,
    },
    queueDetailItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      paddingVertical: 8,
    },
    queueDetailTrackMeta: {
      flex: 1,
      gap: 2,
    },
    queueDetailTrackName: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '600',
    },
    queueDetailTrackArtist: {
      color: theme.muted,
      fontSize: 12,
    },
    queueDetailRemoveButton: {
      alignItems: 'center',
      height: 32,
      justifyContent: 'center',
      width: 32,
    },
    queueClearButton: {
      alignItems: 'center',
      alignSelf: 'flex-end',
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 4,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    queueClearText: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: '600',
    },

    // ── Search improvements ────────────────────────────────────────────────────
    searchLoadingRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      paddingVertical: 24,
    },
    searchLoadingText: {
      color: theme.muted,
      fontSize: 14,
    },
    searchEmptyHero: {
      alignItems: 'center',
      gap: 12,
      paddingVertical: 40,
    },
    searchEmptyIcon: {
      alignItems: 'center',
      backgroundColor: theme.surfaceSoft,
      borderRadius: 40,
      height: 80,
      justifyContent: 'center',
      width: 80,
    },
    searchEmptyTitle: {
      color: theme.text,
      fontSize: 17,
      fontWeight: '700',
    },
    searchEmptySubtitle: {
      color: theme.muted,
      fontSize: 14,
      textAlign: 'center',
    },
    searchCategoryLabel: {
      color: theme.muted,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.6,
      marginBottom: 4,
      marginTop: 12,
      paddingHorizontal: 4,
      textTransform: 'uppercase',
    },
  });
